<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>YES_option_chb_where_agency</name>
   <tag></tag>
   <elementGuidId>fec7ecdb-f583-44f9-9529-507ae5d3b7a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;medicalForm&quot;]/fieldset/table/tbody/tr[30]/td/table/tbody/tr/td/div[1]/div/div[2]/div[2]/label[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#medicalForm > fieldset > table > tbody > tr:nth-child(32) > td > table > tbody > tr > td > div:nth-child(1) > div > div.cont-opt.m-lopt-105 > div.col-xs-7.p-0 > label:nth-child(2) > input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;medicalForm&quot;]/fieldset/table/tbody/tr[30]/td/table/tbody/tr/td/div[1]/div/div[2]/div[2]/label[1]/input</value>
   </webElementProperties>
</WebElementEntity>
