<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>YES_option_txt_date</name>
   <tag></tag>
   <elementGuidId>6fb2860c-a089-46c9-8025-4b8e6978f710</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;medicalForm&quot;]/fieldset/table/tbody/tr[30]/td/table/tbody/tr/td/div[1]/div/div[2]/div[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#medicalForm > fieldset > table > tbody > tr:nth-child(32) > td > table > tbody > tr > td > div:nth-child(1) > div > div.cont-opt.m-lopt-105 > div.col-xs-2.p-0 > input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;medicalForm&quot;]/fieldset/table/tbody/tr[30]/td/table/tbody/tr/td/div[1]/div/div[2]/div[1]/input</value>
   </webElementProperties>
</WebElementEntity>
