<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chb_1_early</name>
   <tag></tag>
   <elementGuidId>51342d55-fb04-4638-9952-70e06a19c7fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;oasisForm&quot;]/fieldset/table/tbody/tr[35]/td[2]/table/tbody/tr/td/div/div[1]/label[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#oasisForm > fieldset > table > tbody > tr:nth-child(36) > td.oasis__answer > table > tbody > tr > td > div > div.ng-scope.ng-isolate-scope > label:nth-child(1) > input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;oasisForm&quot;]/fieldset/table/tbody/tr[35]/td[2]/table/tbody/tr/td/div/div[1]/label[1]/input</value>
   </webElementProperties>
</WebElementEntity>
