<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_username</name>
   <tag></tag>
   <elementGuidId>c6a12cd5-a5f0-4953-a7b4-0d24f0e2b297</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#loginemail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#loginemail</value>
   </webElementProperties>
</WebElementEntity>
