<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_password</name>
   <tag></tag>
   <elementGuidId>52952ef1-3377-4c0b-90d2-3fecc691407b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#loginpassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#loginpassword</value>
   </webElementProperties>
</WebElementEntity>
