<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>YES_option_txt_other</name>
   <tag></tag>
   <elementGuidId>a8fc2afc-1f87-4c4c-9464-c8e0223ada77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;medicalForm&quot;]/fieldset/table/tbody/tr[32]/td/table/tbody/tr/td/div[1]/div/div[2]/div[3]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>#medicalForm > fieldset > table > tbody > tr:nth-child(32) > td > table > tbody > tr > td > div:nth-child(1) > div > div.cont-opt.m-lopt-105 > div.col-xs-3.p-0 > input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;medicalForm&quot;]/fieldset/table/tbody/tr[32]/td/table/tbody/tr/td/div[1]/div/div[2]/div[3]/input</value>
   </webElementProperties>
</WebElementEntity>
