<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chb_2_asian</name>
   <tag></tag>
   <elementGuidId>49e5f2e0-e55e-43a0-a0d4-90084f51fbb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#M0140_ETHNIC_ASIAN</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;M0140_ETHNIC_ASIAN&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#M0140_ETHNIC_ASIAN</value>
   </webElementProperties>
</WebElementEntity>
