<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chb_crohns_disease</name>
   <tag></tag>
   <elementGuidId>412612bc-1368-41d4-a28f-62b402481eab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;medicalForm&quot;]/fieldset/table/tbody/tr[13]/td/table/tbody/tr/td[2]/div[1]/label/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#medicalForm > fieldset > table > tbody > tr:nth-child(13) > td > table > tbody > tr > td:nth-child(2) > div:nth-child(1) > label > input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;medicalForm&quot;]/fieldset/table/tbody/tr[13]/td/table/tbody/tr/td[2]/div[1]/label/input</value>
   </webElementProperties>
</WebElementEntity>
