<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chb_No_History</name>
   <tag></tag>
   <elementGuidId>db2d2caf-b458-4aaa-9cb9-7a523ebc6915</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;medicalForm&quot;]/fieldset/table/tbody/tr[12]/td/table/tbody/tr/td[2]/div/label/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#medicalForm > fieldset > table > tbody > tr:nth-child(12) > td > table > tbody > tr > td:nth-child(2) > div > label > input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;medicalForm&quot;]/fieldset/table/tbody/tr[12]/td/table/tbody/tr/td[2]/div/label/input</value>
   </webElementProperties>
</WebElementEntity>
